apiVersion: v2
name: todo-list
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: mariadb
    version: 11.3.3
    repository: http://helm.ocp4.example.com/charts
